; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino

; These flags force Serial.print to use the Type-C USB port
build_flags = 
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON

; Add the Adafruit INA219 library
lib_deps = 
    adafruit/Adafruit INA219 @ ^1.2.2

; Set the terminal monitor speed
monitor_speed = 115200

; Note: Change upload_protocol to 'dfu' or 'hid' if you upload via USB directly, 
; or leave as 'stlink' if you use an ST-Link programmer.
upload_protocol = stlink

